config/routes.rb
Rails.application.routes.draw do
 resources :profesores
  devise_for :users
  resources :articulos
    resources :articulos do
        collection do
          match 'search' => 'articulos#search', via: [:get, :post], as: :search
         end
  end

  get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/contact'

  get 'static_pages/about'

 match '/home', to: 'static_pages#home',  via: 'get'
 match '/help',    to: 'static_pages#help',  via: 'get'
 match '/about',   to: 'static_pages#about',  via: 'get'
 match '/contact', to: 'static_pages#contact',  via: 'get'

 root :to => 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/articulo.rb
class Articulo < ApplicationRecord
      def self.search(search, page)
                 where(['upper(nombre) like ?',
           "%#{search}%".upcase]).paginate(page: page, per_page: 5).order("nombre");
          
     end
end

app/models/profesor.rb
class Profesor < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/articulos_controller.rb
class ArticulosController < ApplicationController
  before_action :set_articulo, only: [:show, :edit, :update, :destroy]

  # GET /articulos
  # GET /articulos.json
  def search
    index
    render :index
  end
  def index
      @articulos= Articulo.search(params[:search], params[:page])
  end


  # GET /articulos/1
  # GET /articulos/1.json
  def show
  end

  # GET /articulos/new
  def new
    @articulo = Articulo.new
  respond_to { |format| format.js }
  
  end

  # GET /articulos/1/edit
  def edit
  end

  # POST /articulos
  # POST /articulos.json
  def create
    @articulo = Articulo.new(articulo_params)

    respond_to do |format|
      if @articulo.save
        format.html { redirect_to @articulo, notice: 'Articulo was successfully created.' }
        format.json { render :show, status: :created, location: @articulo }
      else
        format.html { render :new }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articulos/1
  # PATCH/PUT /articulos/1.json
  def update
    respond_to do |format|
      if @articulo.update(articulo_params)
        format.html { redirect_to @articulo, notice: 'Articulo was successfully updated.' }
        format.json { render :show, status: :ok, location: @articulo }
      else
        format.html { render :edit }
        format.json { render json: @articulo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articulos/1
  # DELETE /articulos/1.json
  def destroy
    @articulo.destroy
    respond_to do |format|
      format.html { redirect_to articulos_url, notice: 'Articulo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_articulo
      @articulo = Articulo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def articulo_params
      params.require(:articulo).permit(:titulo, :contenido)
    end
end

app/controllers/profesores_controller.rb
class ProfesoresController < ApplicationController
  before_action :set_profesor, only: [:show, :edit, :update, :destroy]

  # GET /profesores
  # GET /profesores.json
  def index
    @profesores = Profesor.all
  end

  # GET /profesores/1
  # GET /profesores/1.json
  def show
  end

  # GET /profesores/new
  def new
    @profesor = Profesor.new
  end

  # GET /profesores/1/edit
  def edit
  end

  # POST /profesores
  # POST /profesores.json
  def create
    @profesor = Profesor.new(profesor_params)

    respond_to do |format|
      if @profesor.save
        format.html { redirect_to @profesor, notice: 'Profesor was successfully created.' }
        format.json { render :show, status: :created, location: @profesor }
      else
        format.html { render :new }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profesores/1
  # PATCH/PUT /profesores/1.json
  def update
    respond_to do |format|
      if @profesor.update(profesor_params)
        format.html { redirect_to @profesor, notice: 'Profesor was successfully updated.' }
        format.json { render :show, status: :ok, location: @profesor }
      else
        format.html { render :edit }
        format.json { render json: @profesor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profesores/1
  # DELETE /profesores/1.json
  def destroy
    @profesor.destroy
    respond_to do |format|
      format.html { redirect_to profesores_url, notice: 'Profesor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profesor
      @profesor = Profesor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profesor_params
      params.require(:profesor).permit(:nombre, :apellido, :cedula, :telefono, :user_id)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
before_action :authenticate_user!, :except => [:home, :help, :contact, :about]
 
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articulos_helper.rb
module ArticulosHelper
end

app/helpers/profesores_helper.rb
module ProfesoresHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articulos/_form.html.erb
<%= simple_form_for @articulo, html: { class: 'form-horizontal', multipart: true, remote: true   } do |f| %>
<br><br>
  <div class="col-md-4">
  <div class="list-group">
    <label for="titulo" class="col-sm-3">Titulo:</label>
   <%= f.text_field :titulo, class: "form-control", class:"text-bold" %>
    <label for="contenido" class="col-sm-3">Contenido:</label>
    <%= f.text_area :contenido, class:"form-control" %>
  </div>
  <br>
      <div  class="actions">
      <%= f.submit "Guardar", class: "btn btn-primary" %>  ||  
      <%= link_to 'Atrás', articulos_path, class:"btn btn-warning" %>
    </div>
  
</div>
</div>
<br>


<% end %>
    

app/views/articulos/edit.html.erb
<h1>Editando Articulo</h1>

<%= render 'form', articulo: @articulo %>

<div class="row">
<div class="col-md-8">
<%= link_to 'Ver', @articulo, class:"btn btn-success" %> |
<%= link_to 'Atrás', articulos_path, class:"btn btn-warning" %>
</div>
</div>

app/views/articulos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articulos</h1>
<div class="well well-sm">
  <div class="well well-sm">

      <label>Busqueda: </label>
      <div class="form-group">
      <%= f.search_field :titulo_or_contenido_cont,:class => "form-control",
             placeholder: "Busqueda avanzada", size: "50"  %>


  </select>
      </div>
      <submit class="btn btn-success btn-sm">
          <%= image_tag("search.png") %>
      </submit>

  <% end %>
</div>

<div class="comtainer">
    <div class="col-md-12">
  <div class="row">
<div class="col-md-8">   
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Contenido</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articulos.each do |articulo| %>
      <tr>
        <td><%= articulo.titulo %></td>
        <td><%= articulo.contenido %></td>
        <td><%= link_to 'Ver', articulo, class: "btn btn-success" %></td>
        <td><%= link_to 'Editar', edit_articulo_path(articulo), class:"btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', articulo, method: :delete, data: { confirm: 'Seguro que quieres elimninarlo?' }, class:"btn btn-danger"%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
  </div>
</div>
<br>
<div class="col-xs-3 col-md-8">
<%= link_to 'Nuevo Articulo', new_articulo_path,class:"btn btn-info", remote:true %>
</div>

<%= will_paginate @articulos, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
<br>
Articulos: <%= @articulos.count %>
<br><br>
<div class="col-xs-3 col-md-8">
<div id="form"></div>
</div>
<%=render'dsfd'%>
///////////////////////////////

app/views/articulos/new.html.erb
<h1>Registrar nuevo Articulo</h1>

<%= render 'form', articulo: @articulo %>

app/views/articulos/new.js.erb
$('#form').html("<%= j render 'articulos/form'%>") 

app/views/articulos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Titulo:</strong>
  <%= @articulo.titulo %>
</p>

<p>
  <strong>Contenido:</strong>
  <%= @articulo.contenido %>
</p>

<%= link_to 'Editar', edit_articulo_path(@articulo),class:"btn btn-warning" %> |
<%= link_to 'Atrás', articulos_path, class:"btn btn-danger" %>

app/views/layouts/_footer.html.erb
<footer class="footer">
 <small>
    By MYNOMBRE Todos los derechos reservados © 2016 ::.
 </small>
 <nav>
    <ul>
     <li><a href="http://www.MIPAGINA.co/">MYCOMPAÑIA</a></li>
    </ul>
 </nav>
</footer>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav id="navegador" class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<% if user_signed_in? %>
  <li><%= link_to "Profesores", articulos_path %></li>

  <li><%= link_to 'Editar Cuenta', edit_user_registration_path %></li>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="true">Admin <span class="caret"></span></a>
    <ul class="dropdown-menu" role="menu">
      <li><%= link_to "Articulos", articulos_path %></li>
    </ul>
  </li>
  <li><%= link_to 'Salir', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Ingresar', new_user_session_path %></li>
  <li><%= link_to 'Crear Usuario', new_user_registration_path %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Biblioteca" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Biblioteca" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
      <%= render 'layouts/footer' %>
  </body>
</html>

app/views/profesores/_form.html.erb
<%= simple_form_for(@profesor) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nombre %>
    <%= f.input :apellido %>
    <%= f.input :cedula %>
    <%= f.input :telefono %>
    <%= f.association :user %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/profesores/edit.html.erb
<h1>Editing Profesor</h1>

<%= render 'form', profesor: @profesor %>

<%= link_to 'Show', @profesor %> |
<%= link_to 'Back', profesores_path %>

app/views/profesores/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profesores</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Cedula</th>
      <th>Telefono</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profesores.each do |profesor| %>
      <tr>
        <td><%= profesor.nombre %></td>
        <td><%= profesor.apellido %></td>
        <td><%= profesor.cedula %></td>
        <td><%= profesor.telefono %></td>
        <td><%= profesor.user %></td>
        <td><%= link_to 'Ver', profesor, class:"btn btn-sucess" %></td>
        <td><%= link_to 'Editar', edit_profesor_path(profesor), class:"btn btn-warning" %></td>
        <td><%= link_to 'Eliminar', profesor, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profesor', new_profesor_path %>

<%= will_paginate @profesores, :previous_label => '&laquo; Anterior', :next_label => 'Siguiente &raquo;' %>
<br>
Profesores: <%= @profesores.count %>

app/views/profesores/new.html.erb
<h1>New Profesor</h1>

<%= render 'form', profesor: @profesor %>

<%= link_to 'Back', profesores_path %>

app/views/profesores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @profesor.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @profesor.apellido %>
</p>

<p>
  <strong>Cedula:</strong>
  <%= @profesor.cedula %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @profesor.telefono %>
</p>

<p>
  <strong>User:</strong>
  <%= @profesor.user %>
</p>

<%= link_to 'Edit', edit_profesor_path(@profesor) %> |
<%= link_to 'Back', profesores_path %>

app/views/static_pages/_error_message.html.erb
<% if model.errors.any? %>
 <div class="alert alert-danger">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <strong><%=  t('errors.template.header', :model => model.class, :count => model.errors.count)%></strong>
    <ul>
     <% model.errors.full_messages.each do |msg| %>
       <li><%= msg.html_safe %></li>
     <% end %>
    </ul>
 </div>
<% end %>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>